In [2]:
from google.colab import drive
drive.mount('/content/drive')
%run "/content/drive/MyDrive/Research/Masters Thesis/V1/0. Parent Code.ipynb"

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pickle5
  Downloading pickle5-0.0.12-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (256 kB)
     |████████████████████████████████| 256 kB 5.0 MB/s
Installing collected packages: pickle5
Successfully installed pickle5-0.0.12
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
2401

#Select the required texts from LinkedIn

In [3]:
#Create labeled and unlabeled text list 


# sex, name, degree_connection, current_location, current_industry, number_connection, 
# edu1, edu2, edu3, edu4, edu5, edu6, 
# number_skills, skills_list, skills_endorsement_pair, Intersts, summary,
# employment

# Education is iteself and object with the following attributes
# SName, SLevel, SDates, SField, SDegree

#Here employment is a list of jobs where each job contains information below 
# [title, company_name, job_dates, job_location, job_summary, job_skills]


labeled_list = []
labeled_list_label = []
unlabeled_list = []
object_number =0
info_list_labeled = []
info_list_unlabeled = []
for ind in object_list:

    for job in ind.employment:
        if job[4]!=None and job[5]!=None and len(job[5]) >= 5:
            split_description = job[4].split("\n skill : ")
            if len(split_description) == 2 :
                info_list_labeled.append([ object_number ]+ job)
                labeled_list.append(job[4])
                labeled_list_label.append(job[5])
            else:
                print(split_description)
                a = "Error Check" + 1
            
        elif  job[4]!=None: 
            info_list_unlabeled.append([ object_number ]+ job)
            unlabeled_list.append(job[4])
    
    object_number = object_number  +1

    # print("______________________")

print(len(labeled_list))
print(len(info_list_labeled))
print(len(unlabeled_list))
print(len(info_list_unlabeled))

1171
1171
14182
14182

In [4]:
import random
random_num = random.sample(range(0,len(info_list_unlabeled)), 1)[0]
info_list_unlabeled[random_num]

[2151,
 'Life Skills Coach/Office Assistant',
 ['The First Tee', None],
 ['Apr 2007 – Aug 2011', '4 yrs 4 mos'],
 'Rockford, IL',
 '\n impact the life of child and youth by build character , instill life - enhance value , and promote healthy choice through the game of golf . ',
 None]

In [5]:
import random
random.sample(range(0,len(info_list_unlabeled)), 1)[0]

13468

# Loading created location and title crosswalks

In [6]:
title_crosswalk = pd.read_excel(main_link + "Input/Linked_titles_LinkedIn_ONET.xlsx" )
location_link = pd.read_excel(main_link + "Input/LinkedIn_location_state.xlsx" )
ONET_SOC18_crosswalk = pd.read_excel(main_link + "Input/2019ONET_to_SOC_Crosswalk.xlsx" ) 
SOC10_SOC18_crosswalk = pd.read_excel(main_link + "Input/soc_2010_to_2018_crosswalk.xlsx" )
SOC00_SOC10_crosswalk = pd.read_excel(main_link + "Input/soc_2000_to_2010_crosswalk.xlsx" )


if "Unnamed: 0" in title_crosswalk.columns:title_crosswalk = title_crosswalk.drop(columns=["Unnamed: 0"])
if "Unnamed: 0" in location_link.columns:location_link = location_link.drop(columns=["Unnamed: 0"])

Crosswalks 


1.   LinkedIn ONET, Occupations titles 
2.   LinkedIn Location to State
3.   ONET SOC to SOC 2018
4.   SOC 2010 to SOC 2018 
5.   SOC 2000 to SOC 2010

In [7]:
# LinkedIn ONET, Occupations titles
Dict_LinkedIn_ONET_titles = dict(zip(title_crosswalk.LinkedIn_titles, title_crosswalk.ONET_titles))
print(Dict_LinkedIn_ONET_titles["Data Input"])

Data Input Clerk

In [8]:
# LinkedIn Location to State
Dict_LinkedIn_State_titles = dict(zip(location_link["LinkedIn_location"], location_link["State"]))
print(Dict_LinkedIn_State_titles["Delaware, United States"])

Delaware

In [73]:
# ONET SOC to SOC 2018
ONET_SOC18_crosswalk["2018 SOC Title"] = ONET_SOC18_crosswalk["2018 SOC Title"].str.lower()
ONET_SOC18_crosswalk["2018_SOC_num"] = ONET_SOC18_crosswalk["2018 SOC Code"].apply(lambda x : x.replace("-",""))
ONET_SOC18_crosswalk= ONET_SOC18_crosswalk.copy()
Dict_OnetSOC_ACS_SOC = dict(zip(ONET_SOC18_crosswalk["O*NET-SOC 2019 Title"], ONET_SOC18_crosswalk["2018_SOC_num"]))
print(Dict_OnetSOC_ACS_SOC["Legislators"])

111031

In [10]:
# SOC 2010 to SOC 2018 
SOC10_SOC18_crosswalk["2010_SOC_Title"] = SOC10_SOC18_crosswalk["2010_SOC_Title"].apply(lambda x : re.sub(r'[^\w]', ' ', x).strip().lower())
SOC10_SOC18_crosswalk["2018_SOC_Title"] = SOC10_SOC18_crosswalk["2018_SOC_Title"].apply(lambda x : re.sub(r'[^\w]', ' ', x).strip().lower())
SOC10_SOC18_crosswalk=SOC10_SOC18_crosswalk.copy()
Dict_SOC10_SOC18 = dict(zip(SOC10_SOC18_crosswalk["2010_SOC_Title"], SOC10_SOC18_crosswalk["2018_SOC_Title"]))
print(Dict_SOC10_SOC18["radar and sonar technicians"])

engineering technologists and technicians  except drafters  all other

In [11]:
# SOC 2000 to SOC 2010
SOC00_SOC10_crosswalk["2010_SOC_title"] = SOC00_SOC10_crosswalk["2010_SOC_title"].apply(lambda x : re.sub(r'[^\w]', ' ', x).strip().lower())
SOC00_SOC10_crosswalk["2000_SOC_title"] = SOC00_SOC10_crosswalk["2000_SOC_title"].apply(lambda x : re.sub(r'[^\w]', ' ', x).strip().lower())
SOC00_SOC10_crosswalk=SOC00_SOC10_crosswalk.copy()
Dict_SOC00_SOC10 = dict(zip(SOC00_SOC10_crosswalk["2000_SOC_title"], SOC00_SOC10_crosswalk["2010_SOC_title"]))
print(Dict_SOC00_SOC10["farmers and ranchers"])

farmers  ranchers  and other agricultural managers

[range(0, 10)]

In [69]:
year = 2004

cross_walk_test = pd.read_excel(main_link + "" + "Input/occ_occsoc_crosswalk_2000_onward.xlsx")

def clean_SOC_name(x):

  if isinstance(x, str): 
    pre = x.upper()
    output = pre.replace('*', '').strip()
  else:
    output = None
  return output

for i in range(2004, 2022):
  if i not in [2020]:
    ACS_wage_test = main_link + "Input/ACS PUMS Wages State Level/" + "ACS PUMS Wages " + str(i) +".csv"
    SOC_test = main_link + "Input/ACS SOC/" + "SOC " + str(i) + ".xlsx"

    wage_test = pd.read_csv(ACS_wage_test).rename(columns = {"SOC occuation code 5%":"SOC_name"})
    SOC_test = pd.read_excel(SOC_test).rename(columns = {"Response Label":"SOC_name", "Value": "SOC_num"})[["SOC_name" 	,"SOC_num"]]

    if i not in [2018, 2019]:
      wage_test["SOC_name"] = wage_test["SOC_name"].apply(lambda x : clean_SOC_name(x))
      SOC_test["SOC_name"] = SOC_test["SOC_name"].apply(lambda x :clean_SOC_name(x) )

      if i == 2004:                             cross_walk_test_sub = cross_walk_test[["2000-2004 ACS OCCSOC code", "Occupation title"]].rename(columns = {"2000-2004 ACS OCCSOC code":"SOC_num"})
      elif i in [x for x in range(2005,2010)]:  cross_walk_test_sub = cross_walk_test[["2005-2009 ACS/PRCS OCCSOC code", "Occupation title"]].rename(columns = {"2005-2009 ACS/PRCS OCCSOC code":"SOC_num"})
      elif i in [x for x in range(2010, 2013)]: cross_walk_test_sub = cross_walk_test[["2010-2012 ACS/PRCS OCCSOC", "Occupation title"]].rename(columns = {"2010-2012 ACS/PRCS OCCSOC":"SOC_num"})
      elif i in [x for x in range(2013, 2018)]: cross_walk_test_sub = cross_walk_test[["2013-2017 ACS/PRCS OCCSOC code", "Occupation title"]].rename(columns = {"2013-2017 ACS/PRCS OCCSOC code":"SOC_num"})
      else:                                     cross_walk_test_sub = cross_walk_test[["2018 Onward ACS/PRCS", "Occupation title"]].rename(columns = {"2018 Onward ACS/PRCS":"SOC_num"})

      merged = wage_test.merge(SOC_test, how='left', on="SOC_name")
      merged2 = merged.merge(cross_walk_test_sub, how='left', on="SOC_num")

      print(i, len(merged[merged["SOC_num"].isna()].values), len(wage_test.values), len(merged[merged["SOC_name"].notna()].values))

2004 0 478 478
2005 1 471 471
2006 1 471 471
2007 67 537 537
2008 0 470 470
2009 0 470 470
2010 0 492 492
2011 0 492 492
2012 0 479 479
2013 0 479 479
2014 0 479 479
2015 0 479 479
2016 0 479 479
2017 0 479 479
2021 0 530 530

In [70]:
#Fix crosswalk for year 2018 and 2019
#Connect ACS SOC 2018 to ONET SOC 2018
  # figure out what to do if occ present in ONET SOC 2018 but only in previous ACS SOC

,SOC_name,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,SOC_num,Occupation title
0,MGR-GENERAL AND OPERATIONS MANAGERS,61917.0,83161.0,79993.0,72961.0,86502,80441.0,83249.0,60774.0,86648.0,...,83829,71175.0,63696.0,82901.0,89332.0,69690.0,86546.0,68799.0,111021,General and Operations Managers
1,MGR-CHIEF EXECUTIVES AND LEGISLATORS,125351.0,87387.0,119615.0,152662.0,155818,127876.0,204484.0,192337.0,158371.0,...,153729,138828.0,94882.0,165001.0,140623.0,63508.0,121160.0,92004.0,1110XX,Chief Executives and Legislators
2,MGR-ADVERTISING AND PROMOTIONS MANAGERS,36252.0,55000.0,33516.0,25025.0,81862,68845.0,105970.0,40000.0,59481.0,...,45276,81639.0,28775.0,184130.0,79960.0,39047.0,40937.0,NaN,112011,Advertising and Promotions Managers
3,MGR-MARKETING MANAGERS,40350.0,115000.0,86178.0,69690.0,102837,81697.0,81959.0,45888.0,77697.0,...,80702,62768.0,46320.0,76305.0,90829.0,28751.0,101136.0,34086.0,112021,Marketing Managers
4,MGR-SALES MANAGERS,115174.0,90000.0,108524.0,70217.0,115813,111162.0,99043.0,111135.0,216718.0,...,100360,86236.0,57436.0,109487.0,104098.0,52657.0,99578.0,176979.0,112022,Sales Managers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,MIL-MILITARY OFFICER SPECIAL AND TACTICAL OPER...,47764.0,48969.0,48765.0,NaN,54868,58741.0,0.0,NaN,48125.0,...,51448,NaN,NaN,75322.0,71095.0,3409.0,86884.0,50000.0,551010,Military Officer Special and Tactical Operatio...
526,MIL-FIRST-LINE ENLISTED MILITARY SUPERVISORS,37750.0,81739.0,41977.0,75597.0,58493,54102.0,79616.0,0.0,195000.0,...,59366,41733.0,58522.0,72083.0,48540.0,77238.0,19358.0,65380.0,552010,First-Line Enlisted Military Supervisors
527,MIL-MILITARY ENLISTED TACTICAL OPERATIONS AND ...,15972.0,28326.0,22746.0,931.0,26203,22156.0,11903.0,47833.0,65920.0,...,26465,27955.0,NaN,34825.0,30281.0,NaN,34326.0,37000.0,553010,Military Enlisted Tactical Operations and Air/...
528,"MIL-MILITARY, RANK NOT SPECIFIED",53248.0,45439.0,29592.0,14214.0,50200,54378.0,33539.0,32063.0,42537.0,...,37048,27599.0,8000.0,61409.0,39054.0,6300.0,59814.0,58612.0,559830,"Military, Rank Not Specified"
529,"UNEMPLOYED, WITH NO WORK EXPERIENCE IN THE LAS...",0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,999920,"Unemployed, with No Work Experience in the Las..."

In [64]:
cross_walk_test = pd.read_excel(main_link + "" + "Input/occ_occsoc_crosswalk_2000_onward.xlsx")
cross_walk_test[cross_walk_test["Occupation title"].notna()]

,Unnamed: 0,2000 1% Census OCC code,2000 5% Census OCC code,2000-2004 ACS OCC code,2005-2009 ACS/PRCS OCC code,2010-2012 ACS/PRCS OCC code,2013-2017 ACS/PRCS OCC code,2018 ACS/PRCS OCC code,2000 1% Census OCCSOC code,2000 5% Census OCCSOC code,2000-2004 ACS OCCSOC code,2005-2009 ACS/PRCS OCCSOC code,2010-2012 ACS/PRCS OCCSOC,2013-2017 ACS/PRCS OCCSOC code,2018 Onward ACS/PRCS,Occupation title
0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,Not Applicable (Under 16 years or not in the l...
3,NaN,1,1.0,10.0,NaN,NaN,NaN,NaN,111011,111011,111011,NaN,NaN,NaN,NaN,Chief Executives
4,NaN,NaN,NaN,NaN,10.0,10.0,10.0,10.0,NaN,NaN,NaN,1110XX,1110XX,1110XX,1110XX,Chief Executives and Legislators
5,NaN,2,2.0,20.0,20.0,20.0,20.0,20.0,111021,111021,111021,111021,111021,111021,111021,General and Operations Managers
6,NaN,3,3.0,30.0,NaN,NaN,NaN,NaN,111031,111031,111031,NaN,NaN,NaN,NaN,Legislators
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,NaN,980,980.0,9800.0,9800.0,9800.0,9800.0,9800.0,551000,551010,551010,551010,551010,551010,551010,Military Officer Special and Tactical Operatio...
831,NaN,981,981.0,9810.0,9810.0,9810.0,9810.0,9810.0,552000,552010,552010,552010,552010,552010,552010,First-Line Enlisted Military Supervisors
832,NaN,982,982.0,9820.0,9820.0,9820.0,9820.0,9825.0,553000,553010,553010,553010,553010,553010,553010,Military Enlisted Tactical Operations and Air/...
833,NaN,983,983.0,9830.0,9830.0,9830.0,9830.0,9830.0,559830,559830,559830,559830,559830,559830,559830,"Military, Rank Not Specified"
835,NaN,992,992.0,9920.0,9920.0,9920.0,9920.0,9920.0,559920,559920,999920,999920,999920,999920,999920,"Unemployed, with No Work Experience in the Las..."

In [ ]:
#pip install fuzzymatcher

In [ ]:
import fuzzymatcher
import rapidfuzz
matched_results = fuzzymatcher.fuzzy_left_join(wage_test, SOC_test,
                                            "SOC_name","SOC_name" ,
                                            left_id_col="SOC_name",
                                            right_id_col="SOC_name")
matched_results["JW Score"] = matched_results[["SOC_name_left", "SOC_name_right"]].apply(lambda x: print(x)) #rapidfuzz.distance.JaroWinkler.normalized_similarity(i, j)

In [ ]:
# https://www.census.gov/programs-surveys/cps/technical-documentation/methodology/industry-and-occupation-classification.html

# https://usa.ipums.org/usa-action/variables/OCCSOC#description_section

import os
import glob

wages_values_2004_2009 = []
wages_values_2010_2017 = []
wages_values_2018_2021 = []

a= 0 
os.chdir(main_link + "Input/ACS PUMS Wages State Level/")
for FileList in glob.glob('*.csv'):
        Year = FileList[15:19]
        ACS_PUMS_wage_df = pd.read_csv(main_link + "Input/ACS PUMS Wages State Level/" +FileList )
        wages_long = ACS_PUMS_wage_df.melt(id_vars=['SOC occuation code 5%'], value_vars=ACS_PUMS_wage_df.columns.tolist()[1:])
        wages_long["Year"] = Year
        wages_long["Occ_Group"] = wages_long['SOC occuation code 5%'].apply(lambda x : x[:3].lower())
        wages_long["SOC_code"] = wages_long['SOC occuation code 5%'].apply(lambda x : re.sub(r'[^\w]', ' ', x[4:]).lower().strip())
        wages_long_values = wages_long[["Occ_Group","SOC_code", "Year", "variable", "value" ]].values.tolist()  #
        wages_long_values = [x for x in wages_long_values if x[0].isnumeric() == False]
        
        if int(Year)<2010: wages_values_2004_2009.extend(wages_long_values)
        elif int(Year)<2018: wages_values_2010_2017.extend(wages_long_values)
        elif int(Year)>2017: wages_values_2018_2021.extend(wages_long_values)
        a= a+len(wages_long_values )

print(a)
print(len(wages_values_2004_2009))
print(len(wages_values_2010_2017))
print(len(wages_values_2018_2021))

# occ_industry_pre = []
# for i in wages_values_all: occ_industry_pre.append([i[1], i[0]])



# occ_industry = []
# for l in occ_industry_pre: 
#   if l not in occ_industry : occ_industry.append(l)

# print(len(occ_industry_pre))
# print(len(occ_industry))

416925
144279
196758
75888

In [ ]:
a = [x[1] for x in wages_values_2018_2021]
set([x for x in a if x not in Dict_SOC10_SOC18.keys() ])

In [ ]:


dict = {}
for i in a:
  j = tuple (i[1:4])
  print(i)
  print(j)

In [ ]:
txt = ["565543", "abc", "1","a"]

x = [x for x in txt if x.isnumeric() == False]

print(x)

In [ ]:
my_dict={}

my_dict[('Country','Name')]='Germany'

my_dict[('Ipl','year')]='2014'

my_dict[('student','name')]='Elite'

new_key=('Country','Name')

if new_key in my_dict:

    print( my_dict[new_key] )